services:
  azurite:
    build:
      context: azurite
    ports:
      - "127.0.0.1:${AZURITE_BLOB_PORT:-10000}:10000"
    volumes:
      - go-web-service-azurite:/data

volumes:
  go-web-service-azurite:
