services:
  postgres:
    build:
      context: postgres
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    volumes:
      - go-web-service-postgres:/var/lib/postgresql

volumes:
  go-web-service-postgres:
